In [1]:
import httpx
import numpy as np


In [2]:
# requests
import requests
import pandas as pd
response = requests.get(
    "https://raw.githubusercontent.com/yashLadha/The_Math_of_Intelligence/"
    "master/Week1/ADRvsRating.csv",
    timeout=10
)
with open("t.csv", "w") as f:
    f.write(response.text)

data1 = pd.read_csv("t.csv")
data1.info()


E:\anaconda\envs\pytorchp\Lib\site-packages\requests\__init__.py:113: RequestsDependencyWarning: urllib3 (2.6.3) or chardet (7.2.0)/charset_normalizer (3.4.6) doesn't match a supported version!
  warnings.warn(


<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ADR     1000 non-null   float64
 1   Rating  1000 non-null   float64
dtypes: float64(2)
memory usage: 15.8 KB


In [3]:
url = "https://raw.githubusercontent.com/yashLadha/The_Math_of_Intelligence/master/Week1/ADRvsRating.csv"
data2 = pd.read_csv(url)
data2.info()

<class 'pandas.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype  
---  ------  --------------  -----  
 0   ADR     1000 non-null   float64
 1   Rating  1000 non-null   float64
dtypes: float64(2)
memory usage: 15.8 KB


In [4]:
data2.head()


,ADR,Rating
0,85.0,117.0
1,83.5,110.0
2,78.2,102.0
3,68.1,97.0
4,66.3,86.0


In [5]:

data2n = data2.values
data2n

array([[ 85. , 117. ],
       [ 83.5, 110. ],
       [ 78.2, 102. ],
       ...,
       [ 58.6,  63. ],
       [ 61.8,  62. ],
       [ 44.7,  51. ]], shape=(1000, 2))

In [6]:
data2n2 = data2.to_numpy(

)
data2n2

array([[ 85. , 117. ],
       [ 83.5, 110. ],
       [ 78.2, 102. ],
       ...,
       [ 58.6,  63. ],
       [ 61.8,  62. ],
       [ 44.7,  51. ]], shape=(1000, 2))

In [7]:
data2n3= np.array(data2)
data2n3

array([[ 85. , 117. ],
       [ 83.5, 110. ],
       [ 78.2, 102. ],
       ...,
       [ 58.6,  63. ],
       [ 61.8,  62. ],
       [ 44.7,  51. ]], shape=(1000, 2))

In [8]:
import urllib.request
from io import StringIO
url = "https://raw.githubusercontent.com/yashLadha/The_Math_of_Intelligence/master/Week1/ADRvsRating.csv"
response = urllib.request.urlopen(url, timeout=10)
data = response.read().decode('utf-8')
df = pd.read_csv(StringIO(data))

In [9]:
import numpy as np

url = "https://raw.githubusercontent.com/yashLadha/The_Math_of_Intelligence/master/Week1/ADRvsRating.csv"
# numpy 可以直接从 URL 加载
data4 = np.genfromtxt(url, delimiter=',', skip_header=1)
print(data4[:3])

[[ 85.  117. ]
 [ 83.5 110. ]
 [ 78.2 102. ]]


In [10]:
def load_data():
    response = httpx.get(
    "https://raw.githubusercontent.com/yashLadha/The_Math_of_Intelligence/"
    "master/Week1/ADRvsRating.csv",
    timeout=10,
    )
    lines = response.text.splitlines()
    print(lines[:4])
    data = []
    for item in lines:
        item = item.split(",")
        data.append(item)

    data.pop(0)
    dataset = np.matrix(data)
    return dataset

In [11]:
data = load_data()

['ADR,Rating', '85.0,117.0', '83.5,110.00000000000001', '78.2,102.0']


In [12]:
print(data[:3])

[['85.0' '117.0']
 ['83.5' '110.00000000000001']
 ['78.2' '102.0']]


In [13]:
len_data = data.shape[0]
data_x = np.c_[np.ones(len_data), data[:, :-1]].astype(float)
data_x.shape

(1000, 2)

In [14]:
data_y = data[:, -1]
data_y.dtype
data_y = data_y.astype(float)


In [15]:
def steep_gradient_descent(data_x, data_y, len_data, alpha, theta):

    n = len_data
    prod = np.dot(theta, data_x.transpose())
    prod -= data_y.transpose()
    sum_grad = np.dot(prod, data_x)
    theta = theta - (alpha / n) * sum_grad
    return theta

In [16]:
def sum_of_square_error(data_x, data_y, len_data, theta):
    prod = np.dot(theta, data_x.transpose())
    prod -= data_y.transpose()
    sum_elem = np.sum(np.square(prod))
    error = sum_elem / ( 2 * len_data)
    return error

In [17]:
def linear_regression(data_x, data_y):
    iterations = 10000
    alpha = 0.00015
    no_features = data_x.shape[1]
    len_data = data_x.shape[0] - 1

    theta = np.zeros((1, no_features))

    for i in range(iterations):
        theta = steep_gradient_descent(data_x, data_y, len_data, alpha, theta)
        error = sum_of_square_error(data_x, data_y, len_data, theta)
        print(f"at iteration {i+ 1} - error is {error:5f}" )

    return theta

In [18]:
theta = linear_regression(data_x, data_y)
len_result = theta.shape[1]
print(len_result)


at iteration 1 - error is 174.589356
at iteration 2 - error is 134.479783
at iteration 3 - error is 134.215468
at iteration 4 - error is 134.213600
at iteration 5 - error is 134.213460
at iteration 6 - error is 134.213332
at iteration 7 - error is 134.213204
at iteration 8 - error is 134.213076
at iteration 9 - error is 134.212948
at iteration 10 - error is 134.212820
at iteration 11 - error is 134.212693
at iteration 12 - error is 134.212565
at iteration 13 - error is 134.212437
at iteration 14 - error is 134.212309
at iteration 15 - error is 134.212181
at iteration 16 - error is 134.212053
at iteration 17 - error is 134.211925
at iteration 18 - error is 134.211797
at iteration 19 - error is 134.211669
at iteration 20 - error is 134.211541
at iteration 21 - error is 134.211413
at iteration 22 - error is 134.211285
at iteration 23 - error is 134.211157
at iteration 24 - error is 134.211029
at iteration 25 - error is 134.210901
at iteration 26 - error is 134.210773
at iteration 27 - err

In [19]:
for i in range(len_result):
  print(f"{theta[0,i]:.5f}")

-1.30805
1.43103


In [20]:
print(theta)

[[-1.3080469   1.43103484]]
